name: rightflair
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  
  # STATE MANAGEMENT & ARCHITECTURE
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # FIREBASE
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  firebase_remote_config: ^6.1.2
  firebase_crashlytics: ^5.0.5
  firebase_analytics: ^12.0.4
  firebase_app_check: ^0.4.1+2

  # UI / THEME / COMPONENTS
  flutter_svg: ^2.0.7
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.7.0+2
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0

  # NETWORK % UTILITIES
  dio: ^5.1.2
  path_provider: ^2.1.5
  connectivity_plus: ^4.0.2
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  intl: ^0.20.2
  easy_localization: ^3.0.7

  # LOCAL DATABASE
  shared_preferences: ^2.1.1
  flutter_image_compress: ^1.1.3

  # NAVIGATION
  go_router: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/
